### ISSUE TITLE
The mod isn't working at all.

### ISSUE THREAD

**Issue by SILVERWAVE20** [ghasttear1/RPGMod#12]
No part of the mod is working, if I have certain old mods running, does it make it so this mod doesn't work? I have it in /Risk of Rain 2/Bepinex/Plugins/R2API and I used to have all my mods outside of R2API but some didn't work, so I moved them.

Edit: I tried removing all my mods, moving the mod out of R2API, deleted the config, going back to 1.2.3, etc, nothing worked.

**Comment by djgamerr** [comment]
I can confirm, not working since the RoR update arrived...

**Comment by SILVERWAVE20** [comment]
> 
> 
> I can confirm, not working since the RoR update arrived...

Could also be a BepinEx issue since thats unupdated.

**Comment by ghasttear1** [comment]
Make sure you are using the updated R2API files from the RoR2 Modding discord, the two files needed can be found in the FAQ section towards the start of the post.
