### ISSUE TITLE
Can't load assetBundle

### ISSUE THREAD

**Issue by ZeusesNeckMeat** [ghasttear1/RPGMod#20]
When loading the mod I am seeing the following error:

`[Info   :   BepInEx] Loading [RPGMod 2.0.0]
[Info   : Unity Log] <color=#13d3dd>RPGMod: </color> Config loaded
[Error  : Unity Log] Unable to open archive file: E:/Steam/steamapps/common/Risk of Rain 2/BepInEx/plugins/RPGMod//assetBundle
[Error  : Unity Log] RPGMOD: Failed to load assetbundle`

![image](https://user-images.githubusercontent.com/59264676/71489295-ea053480-27f2-11ea-8e67-86cd3ac53751.png)

I have checked the spelling and the file location just to make sure that it is, in fact, there as well.

EDIT: After taking the screenshot I noticed that the filepaths are different. 
E:\Steam\steamapps\common\Risk of Rain 2\BepInEx\plugins\ghasttear1-RPGMod\RPGMod
E:/Steam/steamapps/common/Risk of Rain 2/BepInEx/plugins/RPGMod//assetBundle

**Comment by TheKingLuckyy** [comment]
If you just take all of the ghasttear1-RPGMod files and put them into the plugin folder it works.

**Comment by ZeusesNeckMeat** [comment]
Oh yeah, fair point. I installed it through the ROR2 Mod Manager so it created all the files paths.
