### ISSUE TITLE
QuestTracker out of Screen

### ISSUE THREAD

**Issue by NemesisXKL** [ghasttear1/RPGMod#23]
Im running 2560 x 1440 and the Quest Tracker is half way out of my screen.

**Comment by Xarishark** [comment]
mee to can we get the correct numbers for 1440 screens?

**Comment by Oaurn** [comment]
The default xPosition is 89.5.  This had the quest tracker barely visible for me at 3440x1440.  Setting the xPosition to 79.5 looks almost perfect for me.

https://imgur.com/a/CJe9LbS
