### ISSUE TITLE
Enemy item drop not working when quests are disabled

### ISSUE THREAD

**Issue by Shumiry** [ghasttear1/RPGMod#25]
Config file attached.

Turning quests back on got it working again.

Current workaround is that I've set the quest timers to 9000.

[com.ghasttear1.rpgmod.txt](https://github.com/ghasttear1/RPGMod/files/4114283/com.ghasttear1.rpgmod.txt)

**Comment by elijan1985** [comment]
you also can set `questPerTypeMax` and `questAmountMax` to 0
