### ISSUE TITLE
Error 502 when downloading

### ISSUE THREAD

**Issue by SirDiego62** [ghasttear1/RPGMod#32]
I've tried manual download and r2modman download and the same error shows up. It doesn't start the download at all, it just waits there a little bit and then shows the error panel. Hope you can solve this!
![Captura de pantalla 2021-02-11 110743](https://user-images.githubusercontent.com/78905260/107623321-7245d380-6c59-11eb-8c01-123248502403.png)
![Captura de pantalla 2021-02-11 111026](https://user-images.githubusercontent.com/78905260/107623563-d072b680-6c59-11eb-835b-529075b8bd66.png)

**Comment by ghasttear1** [comment]
I'm not sure if there is anything on my end that I can do to fix that, I haven't used r2modman before and the screenshot seems to say that it is an error with the thunderstore host.

**Comment by DevilMire** [comment]
Hi. I actually know these issues and normally it's just a wait time, not with any coding. It's just networking issues and all that, so if it still persists it's not the coder, but the network over which the code is trying to come from to you.
