### ISSUE TITLE
Compatibility issues between mods ? with qb by chen.

### ISSUE THREAD

**Issue by benjdidj** [ghasttear1/RPGMod#33]
I play quite heavely modded in singleplayer and your mod doesn't show. i'll try to thin down which mod conflicts...

Here's a list of my mods; 
[modlist.txt](https://github.com/ghasttear1/RPGMod/files/5966359/modlist.txt)

and a log:
[log.txt](https://github.com/ghasttear1/RPGMod/files/5966365/log.txt)

Thx for the mod. it's nice.

**Comment by benjdidj** [comment]
after thinning down the conflict seems to be with chen's qb mod, that add a drone to ror2.
the modlist:
![r2modman_RWTUt3mWG4](https://user-images.githubusercontent.com/72584566/107662838-fbc1c980-6c8a-11eb-9f4d-90261dae69f5.png)

dependencies:
![r2modman_lmZLshDaBX](https://user-images.githubusercontent.com/72584566/107662905-0da36c80-6c8b-11eb-9ab7-60e0a473af88.png)

log:
[log.txt](https://github.com/ghasttear1/RPGMod/files/5966687/log.txt)

**Comment by ghasttear1** [comment]
Fixed in version 3.0.2, thank you for the log file it was very handy.

**Comment by benjdidj** [comment]
cool.
