### ISSUE TITLE
No monster drops, legendary quest rewards only, config file disdained

### ISSUE THREAD

**Issue by Val-Sama** [ghasttear1/RPGMod#6]
Good day.

Using the latest available version of RPGMod (1.1.0), normal and elite monsters drop nothing ; four bosses drop six items ; quests always award legendary items, as seen below.
Additionally, changing the configuration file (placing zeros and ones so as to e.g. keep only common items as quest rewards) and reloading through F6, or even restarting the game entirely, mostly had no effect. "Mostly" because changing the quest window position on screen worked, just not the rest.
No error shows up in the loader. This problem arises with no mod loaded other than RPGMod.

I am using a pirate copy of the game (latest version) ; a mod manager that has given me no trouble so far ; a load of mods that, beside RandomSpices, all work as intended ; playing single player. Deleting the mod's files, including the config file, and installing it anew did not solve the problem.
Please let me know if there is anything I have missed. If you wish me to try a few things, I am open to suggestions as long as they do not involve reinstalling the game.

Wishing you a nice day, or night, and gay modding!
Val-sama

![RPGMod](https://user-images.githubusercontent.com/22856648/57811109-ba288580-7769-11e9-9e62-2bca73053e72.jpg)

**Comment by CoiLatO** [comment]
same problem with a steam version.

**Comment by Achran** [comment]
Hi,

I found that this legendary only drop is due to system set to use comma fir decimal numbers instead of dot. Try to change the numbers in config file from lika 0.35 to 0,35. It worked for us.

**Comment by haraldfw** [comment]
Found [this](https://stackoverflow.com/a/19678636) stackoverflow answer dealing with a similar issue.

You could also try to account for the issue when generating your initial config-file. So generating the file with commas or periods respectively, depending on what the system uses.

**Comment by CoiLatO** [comment]
Achran, haraldfw,
Damn ! You're right ! Well thank you, it works.

**Comment by Val-Sama** [comment]
Changing all dots in the configuration file to commas made it work as intended. Thanks, both of you.

Closing this issue as a result.
