### ISSUE TITLE
Quest description UI not loading properly

### ISSUE THREAD

**Issue by edgedick** [ghasttear1/RPGMod#7]
So the UI will show up, but there's no text or image of the enemy, instead it looks like a series of white circles; specifically it's like the animation for the menu loading in started, and then just didn't finish.  I say this specifically because another mod, StatsDisplay reloads the stats menu every time you open the info screen, and the beginning of the animation is identical to what the quest UI looks like all the time.

This happens whether or not I have other mods installed or activated.

I've attached a screenshot below.

![rpgmodissue](https://user-images.githubusercontent.com/50881647/58116288-f0329300-7bc9-11e9-9e56-1aea81d5b3fb.png)

**Comment by zzjlovefly** [comment]
![image](https://user-images.githubusercontent.com/48754561/58152393-0bbb9d80-7c9f-11e9-8473-9f4f921b90be.png)
may be this problem?

**Comment by edgedick** [comment]
That does seem to be the error I'm getting.

Any idea how to fix it?

**Comment by ghasttear1** [comment]
Fixed in 1.1.1, was broken from the latest update.
